{% set name = "pdfgrep" %}
{% set version = "2.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pdfgrep.org/download/{{ name }}-{{ version }}.tar.gz
  sha256: 0ef3dca1d749323f08112ffe68e6f4eb7bc25f56f90a2e933db477261b082aba

build:
  skip: true  # [win]
  number: 9

requirements:
  build:
    - {{ compiler('cxx') }}
    - pkg-config
  host:
    - poppler
    - libgcrypt
    - pcre
  run:
    - poppler
    - libgcrypt
    - pcre

test:
  commands:
    - pdfgrep --version

about:
  home: https://pdfgrep.org/
  license: GPL-2.0-only
  license_file: LICENSE.txt
  summary: 'A commandline utility to search text in PDF files'
  description: |
    Search for PATTERN in each PDF FILE and print matching lines. By default,
    PATTERN is an extended regular expression.
    pdfgrep tries to be mostly compatible with GNU grep with some PDF-specific
    distinctions and additional options.
  doc_url: https://pdfgrep.org/doc.html
  dev_url: https://gitlab.com/pdfgrep/pdfgrep

extra:
  recipe-maintainers:
    - julozi
